### ISSUE TITLE
README gives the wrong former name

### ISSUE THREAD

**Issue by nemequ** [jbruchon/lzjody#2]
The end of the README says you changed the name from "lzjody" to "lzjody"

    lzjody was initially called "lzjody" and the name was changed to avoid confusion
    with an existing compression algorithm by the same name that is used in the
    ZFS filesystem.

I assume this was a search & replace gone wild, and that you meant "lzjb" for the second instance.

**Comment by jbruchon** [comment]
Fixed, thanks!
