### ISSUE TITLE
Clean up public header

### ISSUE THREAD

**Issue by nemequ** [jbruchon/lzjody#5]
The funcions are in `lzjody_*`, but everything else is unprefixed.

There are lots of what seem to be internal implementation details (the data structure, defines other than the options) in `lzjody.h`—those should probably go in `lzjody.c` or an internal header.

Finally, it would probably be wise to ifdef an `extern "C" { … }` around the functions so C++ linkers don't get confused.

**Comment by jbruchon** [comment]
Header cleanup fixed in f41c00744bb8e0a5f8eae45f4a0cd8d29b13f207 and header C++ guard placed in 06e9ff3743a593a2eb6a507ec0f428333f567fc2
